<?php

namespace AppBundle\Repository;
use ClassesWithParents\D;

/**
 * OrderTicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTicketsRepository extends \Doctrine\ORM\EntityRepository
{
}
