<?php

namespace AppBundle\Repository;

/**
 * OrderTicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTicketsRepository extends \Doctrine\ORM\EntityRepository
{
}
