<?php

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbrTickets(\DateTime $date)
    {
        $qb = $this->createQueryBuilder('t');

        $qb

            ->select('COUNT(t)')
            ->leftJoin('t.orderTickets', 'o')
            ->where('o.visiteDay = :date')
            ->setParameter('date', $date)

        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
